version: 2.1
orbs:
  node: circleci/node@3.0.0
  coverage-reporter: codacy/coverage-reporter@11.9.2
workflows:
  node-tests:
    jobs:
      - coverage
      - node/test
jobs:
  coverage:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test
      - run:
          name: "Sending coverage"
          command: |
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report
